Repository WildCodeSchool/2023-02-js-btz-apollo, pull requests merged in 2023-04, with the labels that each got.

#1 creation de l'architechture de l'appli + installation des dépendances json et router
  package-lock.json
  package.json
  src/App.jsx
  src/components/Cards.jsx
  src/components/Clock.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Info.jsx
  src/components/Logo.jsx
  src/pages/Scene.jsx
Labels: Reviewed, Changes done

#2 import fonts + global variables and CSS structure
  src/App.css
  src/App.jsx
Labels: Reviewed

#3 ajout des images de planètes
  src/assets/images/Jupiter.png
  src/assets/images/Mars.png
  src/assets/images/Mercury.png
  src/assets/images/Neptune.png
  src/assets/images/Pluton.png
  src/assets/images/Saturne.png
  src/assets/images/Uranus.png
Labels: Reviewed

#4 S01 header
  src/App.jsx
  src/assets/images/icone-info.jpg
  src/assets/images/logo-apollo-blc.png
  src/assets/images/logo-apollo.png
  src/components/Clock.jsx
  src/components/Header.css
  src/components/Header.jsx
  src/components/Info.css
  src/components/Info.jsx
  src/components/Logo.css
  src/components/Logo.jsx
Labels: Reviewed

#5 S01 cards
  src/App.css
  src/App.jsx
  src/assets/images/venus.png
  src/components/Cards.css
  src/components/Cards.jsx
  src/components/ExitButton.css
  src/components/ExitButton.jsx
Labels: Changes done

#6 S01 clock
  src/App.jsx
  src/assets/images/icone-info.jpg
  src/assets/images/icone-info.png
  src/components/Clock.jsx
  src/components/Header/Clock.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Info.css
  src/components/Header/Info.jsx
  src/components/Header/Logo.css
  src/components/Header/Logo.jsx
Labels: Reviewed

#7 navbar with image initialisation
  src/App.css
  src/App.jsx
  src/components/Footer.jsx
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/navbar/NavbarItems.jsx
Labels: Reviewed

#8 S01 cards
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Cards.css
  src/components/Cards.jsx
  src/components/ExitButton.css
  src/components/ExitButton.jsx
  src/pages/Scene.css
  src/pages/Scene.jsx
Labels: Reviewed, Changes done

#9 fix Navbar and react-icons calls
  src/App.jsx
  src/components/ExitButton.jsx
Labels: Reviewed

#10 fix css de l'element Clock et ajout overflow hidden a App
  src/App.css
  src/components/Header/Header.css
Labels: Reviewed

#11 S01 api
  package-lock.json
  package.json
  src/pages/Scene.css
  src/pages/Scene.jsx
Labels: Reviewed

#13 css global cards on scene
  package-lock.json
  package.json
  src/App.css
  src/components/Cards.css
  src/components/Cards.jsx
  src/components/ExitButton.jsx
  src/components/Header/Header.css
  src/components/Header/Info.css
  src/components/Header/Logo.css
  src/components/navbar/Navbar.css
  src/components/navbar/NavbarItems.jsx
  src/pages/Scene.css
Labels: Reviewed

#15 transitions des props pour affichage dynamique des cards et ajustemen…
  src/components/Cards.css
  src/components/Cards.jsx
  src/pages/Scene.jsx
Labels: Reviewed

#14 S01 navbar
  package-lock.json
  package.json
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/navbar/NavbarItem.css
  src/components/navbar/NavbarItem.jsx
  src/components/navbar/NavbarItems.jsx
Labels: Reviewed

#16 adding animation on planets names navbar
  src/components/navbar/NavbarItem.css
  src/components/navbar/NavbarItem.jsx
Labels: Reviewed

#18 moons added to each planet card
  src/components/Cards.jsx
Labels: Reviewed

#17 S01 button
  src/App.jsx
  src/components/Cards.jsx
  src/components/ExitButton.css
  src/components/ExitButton.jsx
  src/components/navbar/Navbar.jsx
  src/components/navbar/NavbarItem.jsx
  src/pages/Scene.css
  src/pages/Scene.jsx
Labels: Reviewed

#19 planet rotate animation
  src/components/navbar/NavbarItem.jsx
  src/components/navbar/TurnPlanet.jsx
Labels: Reviewed, Changes done

#20 S01 moon fix
  src/components/Cards.jsx
  src/pages/Scene.jsx
Labels: Reviewed

#22 fix planet name title
  src/components/navbar/NavbarItem.jsx
  src/components/navbar/TurnPlanet.jsx
Labels: Reviewed

#23 Dev
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.jsx
  src/assets/images/Jupiter.png
  src/assets/images/Mars.png
  src/assets/images/Mercury.png
  src/assets/images/Neptune.png
  src/assets/images/Pluton.png
  src/assets/images/Saturne.png
  src/assets/images/Uranus.png
  src/assets/images/icone-info.png
  src/assets/images/logo-apollo-blc.png
  src/assets/images/logo-apollo.png
  src/assets/images/venus.png
  src/components/Cards.css
  src/components/Cards.jsx
  src/components/ExitButton.css
  src/components/ExitButton.jsx
  src/components/Header/Clock.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Info.css
  src/components/Header/Info.jsx
  src/components/Header/Logo.css
  src/components/Header/Logo.jsx
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/navbar/NavbarItem.css
  src/components/navbar/NavbarItem.jsx
  src/components/navbar/TurnPlanet.jsx
  src/pages/Scene.css
  src/pages/Scene.jsx
Labels: Reviewed

#24 merge suite a migration vers vite
  .eslintrc.cjs
  .gitignore
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/index.jsx
  vite.config.js
Labels: Reviewed

#26 S02 code revue
  README.md
  src/App.jsx
  src/assets/images/Jupiter.png
  src/assets/images/Mars.png
  src/assets/images/Mercury.png
  src/assets/images/Neptune.png
  src/assets/images/Pluton.png
  src/assets/images/Saturne.png
  src/assets/images/Uranus.png
  src/assets/images/venus.png
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/Cards.jsx
  src/components/ExitButton.jsx
  src/components/ExitButton/ExitButton.css
  src/components/ExitButton/ExitButton.jsx
  src/components/Header/Clock.jsx
  src/components/Header/Header.jsx
  src/components/Header/Info/Info.css
  src/components/Header/Info/Info.jsx
  src/components/Header/Logo.jsx
  src/components/Header/Logo/Logo.css
  src/components/Header/Logo/Logo.jsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/NavbarItem/NavbarItem.css
  src/components/Navbar/NavbarItem/NavbarItem.jsx
  src/components/Navbar/TurnPlanet.jsx
  src/components/navbar/Navbar.jsx
  src/components/navbar/NavbarItem.jsx
  src/components/navbar/TurnPlanet.jsx
  src/index.js
  src/index.jsx
  src/pages/Scene.jsx
Labels: Reviewed

#31 S02 3d scene
  src/components/Navbar/NavbarItem/NavbarItem.jsx
  src/components/Navbar/TurnPlanet.jsx
  src/components/Objects/Planet.jsx
  src/components/Objects/Sun.jsx
  src/pages/Scene.css
  src/pages/Scene.jsx
Labels: Reviewed

#32 S02 3d scene
  src/components/Navbar/TurnPlanet.jsx
  src/components/Objects/Planet.jsx
  src/components/Objects/Sun.jsx
  src/pages/Scene.jsx
Labels: Reviewed

#34 cleaned console logs
  src/components/Objects/Planet.jsx
  src/components/Objects/Sun.jsx
Labels: Reviewed

#33 S02 loading
  package-lock.json
  package.json
  src/App.jsx
  src/pages/Scene.css
  src/pages/Scene.jsx
Labels: Changes done

#39 S02 moons
  src/components/Navbar/Navbar.css
  src/components/Navbar/NavbarItem/NavbarItem.css
  src/components/Navbar/TurnPlanet.jsx
  src/components/Objects/Moon.jsx
  src/components/Objects/Planet.jsx
  src/pages/Scene.jsx
Labels: Reviewed

#40 S02 - DEV > MASTER
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/images/Jupiter.png
  src/assets/images/Mars.png
  src/assets/images/Mercury.png
  src/assets/images/Neptune.png
  src/assets/images/Pluton.png
  src/assets/images/Saturne.png
  src/assets/images/Uranus.png
  src/assets/images/favicon.ico
  src/assets/images/venus.png
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/CardList/CardList.css
  src/components/CardList/CardList.jsx
  src/components/Cards.jsx
  src/components/ExitButton.jsx
  src/components/ExitButton/ExitButton.css
  src/components/ExitButton/ExitButton.jsx
  src/components/Header/Clock.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Info/Info.css
  src/components/Header/Info/Info.jsx
  src/components/Header/Logo.jsx
  src/components/Header/Logo/Logo.css
  src/components/Header/Logo/Logo.jsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/NavbarItem/NavbarItem.css
  src/components/Navbar/NavbarItem/NavbarItem.jsx
  src/components/Navbar/TurnPlanet.jsx
  src/components/Objects/Moon.jsx
  src/components/Objects/Planet.jsx
  src/components/Objects/Sun.jsx
  src/components/navbar/Navbar.jsx
  src/components/navbar/NavbarItem.jsx
  src/components/navbar/TurnPlanet.jsx
  src/index.jsx
  src/pages/Scene.css
  src/pages/Scene.jsx
  vite.config.js
Labels: Reviewed
